services:
  ontop:
    image: ontop/ontop-endpoint:4.2.0
    restart: unless-stopped
    environment:
      ONTOP_ONTOLOGY_FILE: /opt/ontop/input/university.ttl
      ONTOP_MAPPING_FILE: /opt/ontop/input/university.obda
      ONTOP_PROPERTIES_FILE: /opt/ontop/input/university.properties
      ONTOP_CORS_ALLOWED_ORIGINS: '*'
      ONTOP_DEV_MODE: '${ONTOP_DEV_MODE}'
    ports:
      - '${ONTOP_PORT}:${ONTOP_PORT}'
    volumes:
      - ./obda:/opt/ontop/input
      - ./jdbc:/opt/ontop/jdbc
    networks:
      - federation

networks:
  federation:
    name: federation
