version: '3.4'

services:
  db_vessel:
    build:
      context: ./data/postgres-vessel
      dockerfile: Dockerfile
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    networks:
      - federation
  db_anomaly:
    build:
      context: ./data/postgres-anomaly
      dockerfile: Dockerfile
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
    networks:
      - federation
  dremio:
    image: dremio/dremio-oss:4.9
    ports:
      - "9047:9047"
      - "31010:31010"
      - "45678:45678"
    volumes:
      - ./dremio.conf:/opt/dremio/conf/dremio.conf
    networks:
      - federation

networks:
  federation:
    name: federation
